### ISSUE TITLE
[Prise de décision] Asynchrone, Modèle & Rôles de chacun

### ISSUE THREAD

**Issue by TheoSabattie** [MieuxVoter/Topics#1]
# Conclusion 

La réunion du CA de septembre 2024 a acté sur la proposition de David.  

![image](https://github.com/user-attachments/assets/d508a91a-f822-4be2-8d83-3a854e0ab2a5)
  
# 🔭 Scope: 

- Le but de cette issue est de définir comment nous souhaitons procéder pour les prises de décisions dans l'association mieux voter et qui peut en prendre
- Le but de cette issue N'est PAS de parler des propositions menant à un simple besoin de participation (ex: [Rencontre Européenne](https://t.me/c/1494631278/5214), (qui veut être présent pour représenter l’association))

## 🕐 Pourquoi j'ouvre cette issue

Nous avons besoin d'avancer mais nous peinons à nous retrouver pour le faire.  

Les décisions orales manque de transparence. Quand la décision est connue, le cheminement, les ressources, les discussions permettant sa compréhension ou son acceptation ne sont pas accessibles.

Prendre chaque décision à partir d'un vote sur le regroupement d'un organe complet (Bureau, CA ou AG) me paraît limitant pour avancer efficacement et inviter à l'autonomie.  

La nomination d'un bureau/CA crée une forme de hiérarchie qui peut donner la sensation que l'entièreté de la dynamique décisionnelle (qui permet d'avancer) revient uniquement aux "élus".  
Je pense que nous souhaitons que chaque membre, peu importe son status, puisse entreprendre des projets, prendre des décisions et avancer en autonomie.  
Cependant nous souhaitons rester dans une même cohérence, pour ce faire, nous souhaitons que chaque proposition de décision puisse se faire "challenger" afin d'éviter des risques et rester dans le cadre de la mission de Mieux Voter.

# 📅  Timeline

J'espère pouvoir fermer cette issue d'ici Mercredi prochain (17/04)

# 🌐 Contexte & Ressources:

- [Prise de décisions asynchrone, pourquoi et comment? (B. Delacrétaz)](https://www.youtube.com/watch?v=xkC4zjtAyRc)
- [Comment prendre des décisions dans un environnement de travail asynchrone : Notre méthode chez Alan](https://alan.com/fr-fr/healthybusiness/media/a/decisions-asynchrones-methode-alan)
- [Fonctionnement à MakeSense (call avec Alizée)](https://docs.google.com/document/d/1k-1HByxiP1GzRnIJIZlGQBTS6v_o-501hYv0zFlVKNU/edit#heading=h.pz18n1q2llzs)
- [Les status de l'association](https://drive.google.com/file/d/16sTkssx3QnYNA4eyQOFmHoy3EgqUg8-n/view)

Vous avez un résumé des ressources [ICI](https://docs.google.com/document/d/1k-1HByxiP1GzRnIJIZlGQBTS6v_o-501hYv0zFlVKNU/edit) (même lien que `Fonctionnement à MakeSense`)

# 💡 Proposition:

### :one: Répartition Oral/Écrit

Je vous propose de limiter l'oral et outil de discussion rapide (telegram) à :
- Brainstorming (échange d'idée, rebondissement)
- Point de synchronisation (on en est où, qui est sur quoi)
- Demande de participation

Je vous propose de privilégier l'écrit avec le format que j'ai utilisé ici pour ce qui touche aux décisions.

### :two: Qui peut proposer/décider ? Les rôles

"Proposeur"/Lead: N'importe quel membre, peu importe son "status". 1 seule personne. Se doit de: 
- Solliciter les avis des personnes concernées par la décision et les personnes expertes du sujet. 
- S'engager à mener son sujet jusqu'à une conclusion (relancer les personnes jusqu'à obtenir une réponse si besoin est)
- Spécifier le "décideur" (lui même ou quelqu'un d'autre s'il ne se sent pas)
- Spécifier les "consultés"

"Décideur": N'importe quel membre, peu importe son "status". 1 seule personne. Se doit de: 
- Prendre en compte l'intégralité des informations et trancher sur une décision. (Note: une décision peut être: ne rien faire / ne pas appliquer la proposition)

"Consulté": Max 6 personnes, peu importe leur "status". Se doit de:
- Répondre aux sollicitations en temps et en heure même si c’est simplement pour confirmer qu’ils n’ont rien à ajouter à la discussion.
- En cas de fort désaccord, ils doivent tirer la sonnette d’alarme, et dans le pire des scénarios, remonter l’information jusqu’au CA/Bureau

"Bureau/CA":  
- Consultable si le décideur peine à se prononcer
- Peut mettre un stop s'ils voient un danger pour l'association ou si on dépasse du cadre de l'association  

⚠️ ça sous-entend qu'on devra revoir les status de l'association.  
= on se devra d'être attentif aux propositions.

Quand à l'accessibilité de nos conversations, elles seront accessibles uniquement aux membres de mieux voter.

Note: l'application de cette décision devra se faire une fois que la mission/le cadre de Mieux Voter sera correctement défini.

### :three: Format et outil pour le travail asynchrone

Je vous propose ce format que j'ai utilisé.
Je vous propose github comme outil pour: 
- La gratuité
- Pas de maintenance à faire
- Le formatage MarkDown
- La pérennité de nos données.

# ❓ Questions: 

Je m'attends à ce que seuls les membres du CA répondent. :)  
Merci de spécifier vos accords et mettre les freins/suggestions là où vous voyez du danger sur chaque sujet ( :one: , 
 :two: , :three: ).  

Note: comme il s'agit de la première issue pour valider la manière dont on décide, il est fort probable que l'adoption de cette résolution s'effectue en réunion CA. Les prochaines s'effectueront comme proposé ici.

**Comment by TheoSabattie** [comment]
<details>
<summary>

## Le template github ⬇️ 

</summary>

# Conclusion
_Section à cacher au début et à afficher lors de la fermeture de l'issue en spécifiant qu'est-ce qui a été décidé_

# 🔭 Scope: 

_Définissez le périmètre et clarifier le pourquoi de la discussion, Découpez au maximum vos sujets pour privilégier des petits scopes et vous assurer ainsi de les fermer rapidement_

- Le but de cette issue est de...
- Le but de cette issue N'est PAS de...

## 🕐 Pourquoi j'ouvre cette issue

_Expliquer pourquoi on devrait résoudre ce problème/besoin et pourquoi maintenant_

# 📅  Timeline

_Description sur quand est-ce que vous attendez des retours et quand est-ce que vous comptez fermer cette issue. Privilégiez un maximum de 10 jours et un minimum de 2 jours._

# 🌐 Contexte & Ressources:

_Préciser le contexte et fournir des ressources utiles (liens vers docs, discussions, …)_

# 💡 Proposition:

_Description d'une solution potentielle ou des solutions à choisir_

# ❓ Questions: 

_Partage d'hypothèses et questions précises invitant à infirmer/confirmer, évitez les questions ouvertes. 
Spécifiez:_ 
- _Les "consultés" (personnes concernées par la décision et les personnes expertes du sujet auxquelles vous souhaitez des réponses (6 max))._ 
- _Les informés (pas de limites, pas d'attentes de réponses de leur part)_
- _Si vous ne vous sentez pas de trancher vous même la décision, spécifiez un "décideur"_
</details>

**Comment by davidchavalarias** [comment]
Merci Théo pour cette proposition. Quelques commentaires : 
* convaincu également qu'un outils comme GitHub peut être un bon support mais d'expérience, il cela peut ne pas être accessible pour tout le monde. Mais si c'est le cas, c'est parfait.
* Pour le processus de prise de décision, je suis pour commencer par régler la question du processus de prise de décision au sein du CA puis dans un second temps, voir comment on peut élargir aux autres membres. Pour le CA, je proposerais quelque chose comme : 
 * Chacun peut proposer des actions qui impliquent l'asso et qui doivent faire l'objet de décision
 * pour cela, un projet de résolution est rédigé, un espace de délibération est créé (ex. issue git, pad ou autre) et les autres membres du CA sont informés.
 * Les membres du CA ont X jours (ex. une semaine) pour échanger sur ce projet de résolution et proposer des formulations alternatives.
 * À l'issue des X jours, il y a un vote au JM sur 3 jour et la résolution la mieux évaluée est acceptée uniquement si sa mention majoritaire est supérieure à un seuil donné. 
 * Si ce n'est pas le cas, soit on abandonne, soit on continue à délibérer.
 
J'ai déjà testé ce fonctionnement, ça marche bien et c'est très collégial.

**Comment by TheoSabattie** [comment]
Merci d'avoir pris le temps de répondre @davidchavalarias 👍 

Je prends note du questionnement de l'accessibilité de l'outil, de la transparence et de la responsabilité décisionnelle.  
Je suis parti un peu vite dans mon issue en considérant qu'on souhaitait une politique horizontale. Erreur car nous n'en avons pas discuté. J'ai donc ouvert le sujet dans [une autre issue](https://github.com/MieuxVoter/Topics/issues/3), plus légère. À laquelle je t'invite à répondre également.  

---

Je prends note de ta proposition plus axée 'démocratique' dans son process, mes questionnements ⬇️   

> un espace de délibération est créé
> Les membres du CA ont X jours (ex. une semaine) pour échanger sur ce projet de résolution et proposer des formulations alternatives.

Je ne suis pas sûr de comprendre le fonctionnement, pourrais-tu le détailler ?
Est-ce qu'une seule personne :a: **pointe un problème** ET **propose une solution**, d'autres viennent proposer des changements, cette même personne ( :a: ) propose la version finale et ensuite un vote est effectué ?

Ou 

Est-ce qu'une personne **pointe un problème**, tout le monde propose plein de solutions, la solution est tranchée durant un vote?

**Comment by MurielleReinhardt** [comment]
Beaucoup d'infos ! Je n'ai pas vraiment une proposition de process, simplement concernant le temps de mise en conflit dans ton échange avec Alizée je ne suis pas fan de l'idée de ne pas pouvoir apporter de suggestions sauf si on est franchement contre, je trouve que c'est important de pouvoir discuter avant de valider un projet.

Concernant les outils, je ne maîtrise pas bien cette app encore et pour moi passer par des documents partagés dans des dossiers spécifiques ça aurait été plus intuitif..

Voilà, merci Théo pour le travail !

**Comment by TheoSabattie** [comment]
> je ne suis pas fan de l'idée de ne pas pouvoir apporter de suggestions sauf si on est franchement contre, je trouve que c'est important de pouvoir discuter avant de valider un projet.

Il y a le fait de discuter pour itérer sur des idées (brainstorming/phase de tri d'idées (voir ressource [Prise de décisions asynchrone, pourquoi et comment? (B. Delacrétaz)](https://www.youtube.com/watch?v=xkC4zjtAyRc))).  
Ici, le processus qui est proposé est pour la présentation d'une proposition pour qu'elle se fasse 'challenger'/valider.   
Je n'ai rien contre des **suggestions** d'améliorations tant qu'on reste avec cette idée et que leur application reste au choix du proposeur.

**Comment by davidchavalarias** [comment]
> Merci d'avoir pris le temps de répondre @davidchavalarias 👍
> 
> Je prends note du questionnement de l'accessibilité de l'outil, de la transparence et de la responsabilité décisionnelle. Je suis parti un peu vite dans mon issue en considérant qu'on souhaitait une politique horizontale. Erreur car nous n'en avons pas discuté. J'ai donc ouvert le sujet dans [une autre issue](https://github.com/MieuxVoter/Topics/issues/3), plus légère. À laquelle je t'invite à répondre également.
> 
> Je prends note de ta proposition plus axée 'démocratique' dans son process, mes questionnements ⬇️
> 
> > un espace de délibération est créé
> > Les membres du CA ont X jours (ex. une semaine) pour échanger sur ce projet de résolution et proposer des formulations alternatives.
> 
> Je ne suis pas sûr de comprendre le fonctionnement, pourrais-tu le détailler ? Est-ce qu'une seule personne 🅰️ **pointe un problème** ET **propose une solution**, d'autres viennent proposer des changements, cette même personne ( 🅰️ ) propose la version finale et ensuite un vote est effectué ?
> 
> Ou
> 
> Est-ce qu'une personne **pointe un problème**, tout le monde propose plein de solutions, la solution est tranchée durant un vote?

C'est ça : 
- Une personne **pointe un problème**, 
- tout le monde propose plein de solutions (en se concertant si possible. D'expérience, il n'y en a pas tant que ça au final)
- la solution est tranchée durant un vote au JM avec seuil d'acceptabilité

**Comment by davidchavalarias** [comment]
En gros : quelqu'un soulève un pb, on propose des solutions, le vote décide 1) si c'était vraiment un pb, i.e. si aucune proposition ne passe la barre de la mention majoritaire minimale, il n'y a pas de décision, 2) si au moins une alternative passe la barre, la meilleure dans le classement JM est implémentée. 

Ce processus permet de laisser la possibilité à un large ensemble de personnes de proposer des choses sans pour autant mener à une implémentation si au final ce qui est proposé n'est pas jugé pertinent par le collectif. Et ça laisse toutes celles et ceux qui le souhaitent proposer des solutions.

C'est une méthode que j'ai déjà testée, ça marche bien.

**Comment by davidchavalarias** [comment]
Donc pour résumer, voici une proposition pour initier un cycle de décision engageant pour MV. Je l'écris pour un groupe X (ex. le CA) et on peut commencer à l'appliquer au CA qui pourra lui même l'élargir à n'importer quel entité, par ex. l'AG si c'est pertinent :
1. Chaque membre du groupe X peut proposer des actions pour lesquelles elle/il souhaite l'implication de moyens humains ou financiers de l'asso en proposant un projet de résolution. Celui-ci est rendu public dans un espace partagé et les autres membres du groupe X en sont informés.
2. Les autres membres du groupe X ont N jours (ex. une semaine) pour échanger sur ce projet de résolution et proposer des formulations alternatives dans ce même espace public.
3. À l'issue de cette période de délibération, l'initiateur de la délibération organise un vote au JM sur 3 jours (durée à définir) auquel participent tous les membres du groupe X. Le vote comporte une meta question : "Quelle la mention majoritaire minimale que doit recueillir une option pour pouvoir faire l'objet d'une décision ?"
4. A la fin du vote, la résolution la mieux évaluée est acceptée uniquement si sa mention majoritaire est supérieure à la mention majoritaire obtenue par la meta-question. Si ce n'est pas le cas, soit on abandonne le projet de décision, soit on retourne en 2. pour formuler d'autres alternatives.

**Comment by TheoSabattie** [comment]
Hello David, 

Merci pour les clarifications.  

Je me permets de re-pointer [les différentes phases dans un cycle de prise de décision présenté par B. Delacrétaz](https://youtu.be/xkC4zjtAyRc?t=420)

- Brainstorming: itérations sur des idées
- Clarifier les besoins/problèmes pour réduire le nombre d’idée en conservant celles qui sont réalistes (= limiter à 3-7, découper en de plus petits problèmes/sujets si on n’y parvient pas)
- Consensus => éprouver les idées et trier pour en faire émerger qu’une seule
- Décisions => Formaliser le choix

Ce que j'avais pointé au CA d'avril, [appuyé sur les ressources d'Alan](https://alan.com/fr-fr/healthybusiness/media/a/decisions-asynchrones-methode-alan), c'est que les 2 premières phases me semblent faisables par un individu, ce qui importe majoritairement, c'est que la proposition finale soit challengée par les membres experts et impactés.

## Sur l'idée d'ouvrir la phase de "brainstorming"

Ce que je ressens majoritairement avec ta proposition, c'est le besoin d'ouvrir les 2 premières phases.  
Là où je peux te rejoindre, c'est l'ouverture au brainstorming pour relever ce qui paraît important à chacun, des valeurs, préciser le problème, les dangers à éviter, rebondir sur des idées, etc...  
Mais je vois plus ça comme un outil pour qu'une seule personne agrége tout ce contenu pour proposer une solution.  
:star: L'idée que chacun puisse proposer une solution alternative me donne la sensation d'une forme de non-confiance en la capacité d'une seule personne de faire de son mieux pour proposer une solution adaptée à un problème.  
C'est une ouverture à une forme de concurrence (au risque d'une bataille d'égo) :star: où la manière de départager peut être dévastateur dans l'esprit d'un "nous". (voir paraph' suivant) 

Je me permets de souligner qu'[Alan](https://alan.com/fr-fr/healthybusiness/media/a/decisions-asynchrones-methode-alan), [Make Sens](https://docs.google.com/document/d/1k-1HByxiP1GzRnIJIZlGQBTS6v_o-501hYv0zFlVKNU/edit#heading=h.pz18n1q2llzs) et [les formats proposés par l'institut du nous (holacratie)](https://partage.universite-du-nous.org/s/MBrNadNkxnc8kgZ) mettent en avant un fonctionnement par [objection](https://partage.universite-du-nous.org/s/AbsG7YzQc28GEiJ) = on passe à une autre solution **uniquement si la précédente solution proposée a des objections qu'on ne parvient pas à résoudre**.

## Sur le départage

> la solution est tranchée durant un vote au JM avec seuil d'acceptabilité

Tout comme le souligne [B. Delacrétaz](https://youtu.be/xkC4zjtAyRc?t=517), le vote crée des camps, ceux qui sont pour, ceux qui sont contre, les gagnants et les perdants.  
Je pense qu'il est donc primordiale de procéder par consentement (la recherche d'un consensus) en premier lieu pour chaque proposition. 
En bref, résoudre toutes les objections avant de retenir une quelconque proposition. 
L'usage du vote devrait être là comme ultra dernier recours, si nous ne trouvons pas de terrain d'entente pour retenir qu'une proposition ou pour formaliser la validation du choix.  

Qu'en dis-tu @davidchavalarias ?

----

Sur le point :star: , j'aimerais bien récolter divers avis. @MurielleReinhardt / @ColineMieuxVoter / @VictoriaMure / @clemencearnautou / @davidchavalarias and other ca members ;)

Quels sont vos points de vue ?  
A-t-on besoin de mettre en concurrence / oppositions plusieurs idées ? (Si oui, dans tous contextes ou dans des contextes spécifiques ? )  
Peut-on faire confiance à l'individuel (étant donnée que le collectif reste présent pour challenger/poser des objections sur une proposition) ?
(...) ;)

**Comment by MurielleReinhardt** [comment]
Merci pour vos argumentaires bien complets. J'ai pas autant de matière pour argumenter et de sources à citer, mais je trouve qu'il est bien de pouvoir proposer des solutions alternatives. Ce n'est pas pour moi de la non-confiance mais de la co-construction : quelqu'un propose une projet de base et quelqu'un d'autre peut partir de cette idée et en avoir une autre qui rend le projet plus pertinent... je ne vois pas ça comme une guerre d'ego et je trouverai ça dommage de se priver de propositions alternatives.
Concernant le vote, j'ai peur qu'une recherche systématique de consensus aboutisse à des heures de discussions pour des futilités, donc je suis pour essayer de discuter puis que l'initiateur du débat propose un vote lorsqu'il sent qu'on arrivera pas à trouver rapidement de consensus.
