### ISSUE TITLE
Dynamique de gouvernance de l'association

### ISSUE THREAD

**Issue by TheoSabattie** [MieuxVoter/Topics#3]
# Conclusion

La majorité des réponses pointent: 
- Une volonté de transparence complète des projets en cours avec des personnes clairement identifiées
- Une liberté / légitimité à entreprendre / mener des projets pour tous nos membres

Comme le souligne @VictoriaMure : 
> pour se sentir en confiance de la faire, il me semble que l'on a collectivement besoin (que ce soit le bureau, le CA ou les bénévoles) de notre feuille de route collective (notre cadre collectif) dans lequel chacun·e pourra développer des choses.

Prochaine étape: rédiger notre cadre / route collective.

# 🔭 Scope: 

- Le but de cette issue est de définir quelle dynamique de gouvernance nous souhaitons pencher pour l'association Mieux Voter

## 🕐 Pourquoi j'ouvre cette issue

Avant de mettre un process de prise de décision, il me paraît important de définir notre idéologie, qu'est-ce qu'on souhaite comme dynamique de gouvernance.

Certains ont pu remarquer plusieurs propositions passer sans réponse dans la boucle AG. 
Cela fait ressortir qu'il y a une forte impression que tout doit être délégué, validé, dirigé par le bureau/CA. Le souhaite-t-on vraiment? Pas sûr. :)

# 📅  Timeline

J'espère pouvoir fermer cette issue d'ici Mercredi prochain (17/04)

# 🌐 Contexte & Ressources:

- [Fonctionnement à MakeSense (call avec Alizée)](https://docs.google.com/document/d/1k-1HByxiP1GzRnIJIZlGQBTS6v_o-501hYv0zFlVKNU/edit#heading=h.pz18n1q2llzs)
- [Ressources partagées de MakeSense](https://make-sense.notion.site/Ressources-ouvertes-sur-la-gouvernance-makesense-6a45b5b68fdc4dc18f57dcaa5b5807ac)
- [Les status de l'association](https://drive.google.com/file/d/16sTkssx3QnYNA4eyQOFmHoy3EgqUg8-n/view)

:star: Quelques propositions sans réponses sur télégram, forme de délégation non explicite (les membres ont-ils un manque de légitimité pour mener eux mêmes leurs projets) ? :  
- https://t.me/c/1494631278/5249
- https://t.me/c/1494631278/5229

### Université du nous, gouvernance partagée:

[Notre rapport au pouvoir](https://vimeo.com/216687171)

[Page que je vous invite à regarder](https://www.gouvernance-partagee.info/formation/parcours-decouverte) . Regardez au minimum les ressources ci-dessous

[Pilotage dynamique sous tension](https://vimeo.com/217131429)
[Définir qui décide quoi ?](https://vimeo.com/212892368)
[Écueils et limites de la gouvernance partagée](https://vimeo.com/219473623)

# 💡 Proposition:

Je vois deux modèles extrêmes:  

### :one: Vertical (Contrôle): 

On considère une forme de rigidité dans la gouvernance. Seuls le bureau/CA, sont légitimes à prendre des décisions / mener des projets/actions. 

### :two: Horizontal (Liberté d'entreprendre): 

On considère une forme de flexibilité dans la gouvernance. On souhaite que chaque membre puisse initier et mener des projets/actions.

---

L'idée est de trancher vers quel **penchant** nous souhaitons aller.   

---

Je pense que :one: va mener à des conversations privées, une forme d'opacité pour les membres lambdas. À contrario, je pense que :two: va mener vers une politique de transparence complète.  

Vis à vis de la ressource :star: , je pense qu'il est préférable de suivre :two: `la liberté d'entreprendre` pour que nos membres se sentent libres de proposer et de mener à bout leurs projets.   
Je souhaite que les personnes proposants des éléments se sentent responsables de mener à bien eux-même leurs projets.  
Je considère que la transparence peut être facteur de motivation et provoquer plus d'engagement chez nos membres.  

Je vois CA/Bureau comme un gardien en cas de besoin (autorité pour mettre un stop par dessus une décision si un risque est détecté pour l'association)

# ❓ Questions: 

Je m'attends à ce que seuls les membres du CA répondent. :)  
- Est-ce que le penchant vers 2️⃣ `Horizontal, Liberté d'entreprendre` est ok pour vous?   
- Des suggestions de fonctionnement mixe (avec quel penchant) ?

**Comment by MurielleReinhardt** [comment]
Je suis pour le 2, mais avec tout de même une personne identifiée responsable du projet (qu'elle soit ou non dans le CA) afin d'avoir une personne garante de l'avancée du projet

**Comment by ColineMieuxVoter** [comment]
Hello, 

Dans le sens de Murielle, je plaiderais pour une approche moins binaire du sujet. A mon sens on peut prendre le meilleur des deux mondes, en offrant une transparence complète sur les projets en cours (dans la limite du confidentiel si certains projets le nécessite, par exemple en lien avec des acteurs politiques) tout en ayant une répartition des responsabilités et du cadre clairs (un porteur de projet, un timing/process de décision clair et partagé).

Comment propose-tu d'avancer sur le sujet ?

**Comment by TheoSabattie** [comment]
Hello @ColineMieuxVoter ,

Merci d'avoir pris le temps de répondre :)

> je plaiderais pour une approche moins binaire du sujet

Peut-être n'ai-je pas été assez clair:

> L'idée est de trancher vers quel **penchant** nous souhaitons aller.

L'idée principale étant de dire : souhaite-t-on s'assurer d'un contrôle par le biais d'élus :one: (CA/bureau/voir autre plus tard) avec une hiérarchie forte (= rien ne peut se faire sans "responsable" prédéfinis) ou souhaite-t-on plutôt laisser de la liberté d'entreprendre à nos membres :two: (= Les "responsables" prédéfinis ne sont pas indispensables pour avancer)

Je **ne** propose **pas** d'adopter un extrême directement mais de se mettre d'accord sur la tendance que nous souhaitons adopter.

> Comment propose-tu d'avancer sur le sujet ?

Si nous sommes tous d'accord pour dire que nous souhaitons la tendance :two: (liberté d'entreprendre pour nos membres), la suite sera de définir la forme plus précisément. Comme vous le mentionnez toutes les deux: un devoir de transparence des membres: des personnes et des avancées identifiables/suivables, etc...

**Comment by VictoriaMure** [comment]
Bonjour à toutes et tous, 

Je pense aussi que l'on doit tendre vers un "entre deux". Je pense aussi que les membres de l'asso doivent pouvoir se sentir légitimes et libre de mener des projets. Toutefois, pour se sentir en confiance de la faire, il me semble que l'on a collectivement besoin (que ce soit le bureau, le CA ou les bénévoles) de notre feuille de route collective (notre cadre collectif) dans lequel chacun·e pourra développer des choses.

**Comment by clemencearnautou** [comment]
Hello, 

Je suis d'accord avec vous, je penche plus sur l'option 2 mais une horizontalité totale n'est pas possible non plus et on peut construire un entre deux ! 

J'aime beaucoup la vision de l'UdN sur le sujet, ils parlent de trois dimensions dans une gouvernance : 
- La verticalité 
- L'horizontalité
- La profondeur 

Je pense qu'il faut des 3 ;)

**Comment by davidchavalarias** [comment]
@TheoSabattie  à mon sens qu'il faut commencer par distinguer différents niveaux de décision en fonction de ce qu'ils impliquent : 
1. une simple action en nom des participants
2. une action au nom de Mieux Voter
3. une action qui nécessite d'engager des fonds de Mieux Voter. 
4. ..

Il faut à la fois de l'horizontalité et de la cohérence moyen terme dans la stratégie globale de Mieux Voter notamment sur les ressources rivales (au sens de l'économie) telles que les financements. 

A chaque fois que 2 ou 3 sont en jeu, il doit y avoir à mon sens un vote d'entités qui représentent MV, soit l'AG, soit le CA soit le Bureau, ce qui permet de moduler le niveau d'horizontalité/verticalité. Sinon, pour 2., cela veut dire qu'on a pas de stratégie d'image, et pour 3, cela veut dire qu'on prive certains d'opportunités sans leur permettre de prendre part à la décision les qui en prive.

Le mode de fonctionnement proposé dans [l'issue 1](https://github.com/MieuxVoter/Topics/issues/1#issuecomment-2050632168) permet de régler cela de manière dynamique et collective en fonction des enjeux.
